package com.example.odysseyglyph

import android.app.Service
import android.content.ComponentName
import android.content.Intent
import android.os.Bundle
import android.os.Handler
import android.os.IBinder
import android.os.Looper
import android.os.Message
import android.os.Messenger
import com.nothing.ketchum.Glyph
import com.nothing.ketchum.GlyphMatrixManager
import com.nothing.ketchum.GlyphToy
import java.io.InputStream

/**
 * Glyph Toy that plays back a pre-baked sequence of 25x25 monochrome frames
 * (generated by video_to_glyph.py) on the Phone (3) Glyph Matrix, looping
 * for as long as the toy is active.
 *
 * Long-pressing the Glyph Button pauses/resumes playback.
 */
class OdysseyToyService : Service() {

    private var glyphManager: GlyphMatrixManager? = null
    private val mainHandler = Handler(Looper.getMainLooper())

    private var frames: List<IntArray> = emptyList()
    private var frameIntervalMs: Long = 83L // ~12fps default, overwritten once frames.bin is read
    private var frameIndex = 0
    private var isPaused = false

    private val playbackRunnable = object : Runnable {
        override fun run() {
            if (frames.isEmpty()) return
            if (!isPaused) {
                glyphManager?.setMatrixFrame(frames[frameIndex])
                frameIndex = (frameIndex + 1) % frames.size
            }
            mainHandler.postDelayed(this, frameIntervalMs)
        }
    }

    private val glyphCallback = object : GlyphMatrixManager.Callback {
        override fun onServiceConnected(componentName: ComponentName) {
            glyphManager?.register(Glyph.DEVICE_23112)
            loadFramesAndStart()
        }

        override fun onServiceDisconnected(componentName: ComponentName) {
            // no-op
        }
    }

    // Handles Glyph Button events (long-press toggles pause/resume)
    private val serviceHandler = object : Handler(Looper.getMainLooper()) {
        override fun handleMessage(msg: Message) {
            if (msg.what == GlyphToy.MSG_GLYPH_TOY) {
                val bundle = msg.data
                if (bundle?.getString(GlyphToy.MSG_GLYPH_TOY_DATA) == GlyphToy.EVENT_CHANGE) {
                    isPaused = !isPaused
                }
            } else {
                super.handleMessage(msg)
            }
        }
    }
    private val serviceMessenger = Messenger(serviceHandler)

    override fun onBind(intent: Intent?): IBinder {
        init()
        return serviceMessenger.binder
    }

    override fun onUnbind(intent: Intent?): Boolean {
        mainHandler.removeCallbacks(playbackRunnable)
        glyphManager?.turnOff()
        glyphManager?.unInit()
        glyphManager = null
        return false
    }

    private fun init() {
        glyphManager = GlyphMatrixManager.getInstance(applicationContext)
        glyphManager?.init(glyphCallback)
    }

    /** Reads app/src/main/assets/frames.bin, written by video_to_glyph.py */
    private fun loadFramesAndStart() {
        Thread {
            try {
                val (loadedFrames, fps) = readFramesAsset(assets.open("frames.bin"))
                frames = loadedFrames
                frameIntervalMs = (1000L / fps).coerceAtLeast(1L)
                frameIndex = 0
                mainHandler.post {
                    mainHandler.removeCallbacks(playbackRunnable)
                    mainHandler.post(playbackRunnable)
                }
            } catch (e: Exception) {
                // Asset missing or malformed — nothing to play. Check that
                // frames.bin was copied into app/src/main/assets/.
                e.printStackTrace()
            }
        }.start()
    }

    /**
     * Binary format written by video_to_glyph.py:
     *   uint32 frameCount (little-endian)
     *   uint32 fps         (little-endian)
     *   frameCount * 625 bytes, one brightness value (0-255) per matrix cell,
     *   row-major 25x25.
     *
     * setMatrixFrame(int[]) expects a 625-length int array (0-255 per cell),
     * so each byte is expanded to an int here.
     */
    private fun readFramesAsset(input: InputStream): Pair<List<IntArray>, Int> {
        val data = input.use { it.readBytes() }

        fun readU32(offset: Int): Int {
            return (data[offset].toInt() and 0xFF) or
                ((data[offset + 1].toInt() and 0xFF) shl 8) or
                ((data[offset + 2].toInt() and 0xFF) shl 16) or
                ((data[offset + 3].toInt() and 0xFF) shl 24)
        }

        val frameCount = readU32(0)
        val fps = readU32(4)
        val cellsPerFrame = 25 * 25

        val result = ArrayList<IntArray>(frameCount)
        var offset = 8
        repeat(frameCount) {
            val arr = IntArray(cellsPerFrame)
            for (i in 0 until cellsPerFrame) {
                arr[i] = data[offset + i].toInt() and 0xFF
            }
            result.add(arr)
            offset += cellsPerFrame
        }
        return Pair(result, if (fps <= 0) 12 else fps)
    }
}
