package com.example.odysseyglyph

import android.app.Service
import android.content.ComponentName
import android.content.Intent
import android.os.Bundle
import android.os.Handler
import android.os.IBinder
import android.os.Looper
import android.os.Message
import android.os.Messenger
import com.nothing.ketchum.Glyph
import com.nothing.ketchum.GlyphMatrixManager
import com.nothing.ketchum.GlyphToy
import java.io.InputStream

/**
 * Glyph Toy that plays back a pre-baked sequence of 25x25 monochrome frames
 * (generated by video_to_glyph.py) on the Phone (3) Glyph Matrix, looping
 * for as long as the toy is active.
 *
 * Long-pressing the Glyph Button pauses/resumes playback.
 */
abstract class BaseToyService : Service() {
    
    abstract fun getFramesFileName(): String

    private var glyphManager: GlyphMatrixManager? = null
    private val mainHandler = Handler(Looper.getMainLooper())

    private var frames: List<IntArray> = emptyList()
    private var frameIntervalMs: Long = 83L // ~12fps default, overwritten once frames.bin is read
    private var frameIndex = 0
    private var isPaused = false
    private var currentPlaybackMode = 1 // 0=ONCE, 1=LOOP, 2=PING_PONG

    private val playbackRunnable = object : Runnable {
        override fun run() {
            if (frames.isEmpty()) return
            if (!isPaused) {
                glyphManager?.setMatrixFrame(frames[frameIndex])
                frameIndex++
                if (frameIndex >= frames.size) {
                    if (currentPlaybackMode == 0) { // ONCE
                        glyphManager?.turnOff()
                        return // Do not post next frame
                    } else {
                        frameIndex = 0
                    }
                }
            }
            mainHandler.postDelayed(this, frameIntervalMs)
        }
    }

    private val glyphCallback = object : GlyphMatrixManager.Callback {
        override fun onServiceConnected(componentName: ComponentName) {
            glyphManager?.register(Glyph.DEVICE_23112)
            loadFramesAndStart()
        }

        override fun onServiceDisconnected(componentName: ComponentName) {
            // no-op
        }
    }

    // Handles Glyph Button events (long-press toggles pause/resume)
    private val serviceHandler = object : Handler(Looper.getMainLooper()) {
        override fun handleMessage(msg: Message) {
            if (msg.what == GlyphToy.MSG_GLYPH_TOY) {
                val bundle = msg.data
                if (bundle?.getString(GlyphToy.MSG_GLYPH_TOY_DATA) == GlyphToy.EVENT_CHANGE) {
                    isPaused = !isPaused
                }
            } else {
                super.handleMessage(msg)
            }
        }
    }
    private val serviceMessenger = Messenger(serviceHandler)

    override fun onBind(intent: Intent?): IBinder {
        init()
        return serviceMessenger.binder
    }

    override fun onUnbind(intent: Intent?): Boolean {
        mainHandler.removeCallbacks(playbackRunnable)
        glyphManager?.turnOff()
        glyphManager?.unInit()
        glyphManager = null
        return false
    }

    private fun init() {
        glyphManager = GlyphMatrixManager.getInstance(applicationContext)
        glyphManager?.init(glyphCallback)
    }

    private var broadcastReceiver: android.content.BroadcastReceiver? = null

    override fun onCreate() {
        super.onCreate()
        broadcastReceiver = object : android.content.BroadcastReceiver() {
            override fun onReceive(context: android.content.Context?, intent: android.content.Intent?) {
                if (intent?.action == "com.example.odysseyglyph.RELOAD_FRAMES") {
                    loadFramesAndStart()
                }
            }
        }
        val filter = android.content.IntentFilter("com.example.odysseyglyph.RELOAD_FRAMES")
        // Exported = false for security
        if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.TIRAMISU) {
            registerReceiver(broadcastReceiver, filter, RECEIVER_NOT_EXPORTED)
        } else {
            registerReceiver(broadcastReceiver, filter)
        }
    }

    override fun onDestroy() {
        super.onDestroy()
        broadcastReceiver?.let { unregisterReceiver(it) }
    }

    /** Reads frames.bin written by VideoProcessor */
    private fun loadFramesAndStart() {
        Thread {
            try {
                val file = java.io.File(filesDir, getFramesFileName())
                if (!file.exists()) {
                    // Fallback to assets if they installed the older hardcoded version
                    val fallback = assets.open(getFramesFileName())
                    val (loadedFrames, fps) = readFramesAsset(fallback)
                    frames = loadedFrames
                    frameIntervalMs = (1000L / fps).coerceAtLeast(1L)
                } else {
                    val input = java.io.FileInputStream(file)
                    val (loadedFrames, fps) = readFramesAsset(input)
                    frames = loadedFrames
                    frameIntervalMs = (1000L / fps).coerceAtLeast(1L)
                }
                
                frameIndex = 0
                mainHandler.post {
                    mainHandler.removeCallbacks(playbackRunnable)
                    mainHandler.post(playbackRunnable)
                }
            } catch (e: Exception) {
                e.printStackTrace()
            }
        }.start()
    }

    /**
     * Binary format written by VideoProcessor:
     *   uint32 frameCount   (little-endian)
     *   uint32 fps          (little-endian)
     *   uint32 playbackMode (little-endian) 0=ONCE, 1=LOOP, 2=PING_PONG
     *   frameCount * 625 bytes, one brightness value (0-255) per matrix cell
     *
     * setMatrixFrame(int[]) expects a 625-length int array (0-4095 per cell),
     * so each byte is expanded to an int here.
     */
    private fun readFramesAsset(input: InputStream): Pair<List<IntArray>, Int> {
        val data = input.use { it.readBytes() }

        fun readU32(offset: Int): Int {
            return (data[offset].toInt() and 0xFF) or
                ((data[offset + 1].toInt() and 0xFF) shl 8) or
                ((data[offset + 2].toInt() and 0xFF) shl 16) or
                ((data[offset + 3].toInt() and 0xFF) shl 24)
        }

        // Check if old 8-byte header or new 12-byte header
        // Since we changed the format, assume new format if data size > 12.
        // Actually, safer to check the file size vs frameCount * 625 + 12
        val frameCountOld = readU32(0)
        val isNewFormat = (data.size - 12) == frameCountOld * 625
        
        var frameCount = frameCountOld
        var fps = readU32(4)
        var playbackMode = 1 // Default to LOOP

        var offset = 8
        if (isNewFormat) {
            playbackMode = readU32(8)
            offset = 12
        } else {
            // Fallback for old format
            frameCount = readU32(0)
            fps = readU32(4)
            offset = 8
        }

        val cellsPerFrame = 25 * 25

        val result = ArrayList<IntArray>(frameCount)
        repeat(frameCount) {
            val arr = IntArray(cellsPerFrame)
            for (i in 0 until cellsPerFrame) {
                // Scale 8-bit (0-255) to 12-bit (0-4095) for the Glyph SDK
                arr[i] = (data[offset + i].toInt() and 0xFF) * 16
            }
            result.add(arr)
            offset += cellsPerFrame
        }
        
        // We'll store playbackMode in a global variable for the Runnable to use
        currentPlaybackMode = playbackMode
        
        return Pair(result, if (fps <= 0) 12 else fps)
    }
}

class OdysseyToyServiceSlot1 : BaseToyService() {
    override fun getFramesFileName() = "frames_slot1.bin"
}

class OdysseyToyServiceSlot2 : BaseToyService() {
    override fun getFramesFileName() = "frames_slot2.bin"
}

class OdysseyToyServiceSlot3 : BaseToyService() {
    override fun getFramesFileName() = "frames_slot3.bin"
}
