package com.example.odysseyglyph

import android.app.Service
import android.content.ComponentName
import android.content.Intent
import android.os.Bundle
import android.os.Handler
import android.os.IBinder
import android.os.Looper
import android.os.Message
import android.os.Messenger
import com.nothing.ketchum.Glyph
import com.nothing.ketchum.GlyphMatrixManager
import com.nothing.ketchum.GlyphToy
import java.io.InputStream

/**
 * Glyph Toy that plays back a pre-baked sequence of 25x25 monochrome frames
 * (generated by video_to_glyph.py) on the Phone (3) Glyph Matrix, looping
 * for as long as the toy is active.
 *
 * Long-pressing the Glyph Button pauses/resumes playback.
 */
abstract class BaseToyService : Service() {
    
    abstract fun getFramesFileName(): String

    private var glyphManager: GlyphMatrixManager? = null
    private var mediaPlayer: android.media.MediaPlayer? = null
    private val mainHandler = Handler(Looper.getMainLooper())

    private var frames: List<IntArray> = emptyList()
    private var frameIntervalMs: Long = 83L // ~12fps default, overwritten once frames.bin is read
    private var currentFps = 12
    private var frameIndex = 0
    private var isPaused = false
    private var currentPlaybackMode = 1 // 0=ONCE, 1=LOOP, 2=PING_PONG
    private var currentAudioOffsetMs = 0
    private var startElapsedMs = 0L

    private val playbackRunnable = object : Runnable {
        override fun run() {
            if (frames.isEmpty()) return
            if (!isPaused) {
                val elapsedMs: Long
                val mp = mediaPlayer
                if (mp != null && mp.isPlaying) {
                    elapsedMs = (mp.currentPosition - currentAudioOffsetMs).toLong()
                } else {
                    elapsedMs = android.os.SystemClock.elapsedRealtime() - startElapsedMs
                }
                
                if (elapsedMs >= 0) {
                    var targetIndex = (elapsedMs * currentFps / 1000L).toInt()
                    
                    if (targetIndex >= frames.size) {
                        if (currentPlaybackMode == 0) { // ONCE
                            glyphManager?.turnOff()
                            return // Do not post next frame
                        } else {
                            targetIndex %= frames.size
                        }
                    }
                    
                    if (targetIndex != frameIndex) {
                        frameIndex = targetIndex
                        glyphManager?.setMatrixFrame(frames[frameIndex])
                    }
                }
            }
            mainHandler.postDelayed(this, 20L) // Poll at 50Hz
        }
    }

    private val glyphCallback = object : GlyphMatrixManager.Callback {
        override fun onServiceConnected(componentName: ComponentName) {
            glyphManager?.register(Glyph.DEVICE_23112)
            loadFramesAndStart()
        }

        override fun onServiceDisconnected(componentName: ComponentName) {
            // no-op
        }
    }

    // Handles Glyph Button events (long-press toggles pause/resume)
    private val serviceHandler = object : Handler(Looper.getMainLooper()) {
        override fun handleMessage(msg: Message) {
            if (msg.what == GlyphToy.MSG_GLYPH_TOY) {
                val bundle = msg.data
                if (bundle?.getString(GlyphToy.MSG_GLYPH_TOY_DATA) == GlyphToy.EVENT_CHANGE) {
                    isPaused = !isPaused
                    if (isPaused) {
                        mediaPlayer?.pause()
                    } else {
                        mediaPlayer?.start()
                        // Shift startElapsedMs so elapsedMs doesn't jump
                        val currentElapsed = (frameIndex * 1000L) / currentFps
                        startElapsedMs = android.os.SystemClock.elapsedRealtime() - currentElapsed
                    }
                }
            } else {
                super.handleMessage(msg)
            }
        }
    }
    private val serviceMessenger = Messenger(serviceHandler)

    override fun onBind(intent: Intent?): IBinder {
        init()
        return serviceMessenger.binder
    }

    override fun onUnbind(intent: Intent?): Boolean {
        mainHandler.removeCallbacks(playbackRunnable)
        glyphManager?.turnOff()
        glyphManager?.unInit()
        glyphManager = null
        mediaPlayer?.release()
        mediaPlayer = null
        return false
    }

    private fun init() {
        glyphManager = GlyphMatrixManager.getInstance(applicationContext)
        glyphManager?.init(glyphCallback)
    }

    private var broadcastReceiver: android.content.BroadcastReceiver? = null

    override fun onCreate() {
        super.onCreate()
        broadcastReceiver = object : android.content.BroadcastReceiver() {
            override fun onReceive(context: android.content.Context?, intent: android.content.Intent?) {
                if (intent?.action == "com.example.odysseyglyph.RELOAD_FRAMES") {
                    loadFramesAndStart()
                }
            }
        }
        val filter = android.content.IntentFilter("com.example.odysseyglyph.RELOAD_FRAMES")
        androidx.core.content.ContextCompat.registerReceiver(
            this,
            broadcastReceiver,
            filter,
            androidx.core.content.ContextCompat.RECEIVER_NOT_EXPORTED
        )
    }

    override fun onDestroy() {
        super.onDestroy()
        broadcastReceiver?.let { unregisterReceiver(it) }
    }

    /** Reads frames.bin written by VideoProcessor */
    private fun loadFramesAndStart() {
        Thread {
            try {
                val file = java.io.File(filesDir, getFramesFileName())
                if (!file.exists()) {
                    // Fallback to assets if they installed the older hardcoded version
                    val fallback = assets.open(getFramesFileName())
                    val (loadedFrames, fps) = readFramesAsset(fallback)
                    frames = loadedFrames
                    currentFps = fps
                    frameIntervalMs = (1000L / fps).coerceAtLeast(1L)
                } else {
                    val input = java.io.FileInputStream(file)
                    val (loadedFrames, fps) = readFramesAsset(input)
                    frames = loadedFrames
                    currentFps = fps
                    frameIntervalMs = (1000L / fps).coerceAtLeast(1L)
                }
                
                // Initialize MediaPlayer if audio exists
                val audioFile = java.io.File(filesDir, getFramesFileName().replace("frames_", "audio_").replace(".bin", ".mp3"))
                mainHandler.post {
                    mediaPlayer?.release()
                    mediaPlayer = null
                    if (audioFile.exists()) {
                        try {
                            mediaPlayer = android.media.MediaPlayer().apply {
                                setDataSource(audioFile.absolutePath)
                                isLooping = (currentPlaybackMode == 1 || currentPlaybackMode == 2)
                                prepare()
                                setVolume(1.0f, 1.0f)
                            }
                        } catch (e: Exception) {
                            e.printStackTrace()
                        }
                    }
                }
                
                frameIndex = 0
                mainHandler.post {
                    mainHandler.removeCallbacks(playbackRunnable)
                    val mp = mediaPlayer
                    if (!isPaused && mp != null) {
                        mp.setOnSeekCompleteListener { mp2 ->
                            mp2.start()
                            startElapsedMs = android.os.SystemClock.elapsedRealtime()
                            mainHandler.post(playbackRunnable)
                        }
                        if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.O) {
                            mp.seekTo(currentAudioOffsetMs.toLong(), android.media.MediaPlayer.SEEK_CLOSEST)
                        } else {
                            mp.seekTo(currentAudioOffsetMs)
                        }
                    } else {
                        startElapsedMs = android.os.SystemClock.elapsedRealtime()
                        mainHandler.post(playbackRunnable)
                    }
                }
            } catch (e: Exception) {
                e.printStackTrace()
            }
        }.start()
    }

    /**
     * Binary format written by VideoProcessor:
     *   uint32 frameCount   (little-endian)
     *   uint32 fps          (little-endian)
     *   uint32 playbackMode (little-endian) 0=ONCE, 1=LOOP, 2=PING_PONG
     *   frameCount * 625 bytes, one brightness value (0-255) per matrix cell
     *
     * setMatrixFrame(int[]) expects a 625-length int array (0-4095 per cell),
     * so each byte is expanded to an int here.
     */
    private fun readFramesAsset(input: InputStream): Pair<List<IntArray>, Int> {
        val data = input.use { it.readBytes() }

        fun readU32(offset: Int): Int {
            return (data[offset].toInt() and 0xFF) or
                ((data[offset + 1].toInt() and 0xFF) shl 8) or
                ((data[offset + 2].toInt() and 0xFF) shl 16) or
                ((data[offset + 3].toInt() and 0xFF) shl 24)
        }

        // Check if old 8-byte header, 12-byte header, or new 16-byte header
        val frameCountOld = readU32(0)
        var bytesPerFrame = 625
        val isNewFormat = (data.size - 12) > 0 && (data.size - 12) % frameCountOld == 0
        val isFormatV3 = (data.size - 16) > 0 && (data.size - 16) % frameCountOld == 0
        
        if (isFormatV3) bytesPerFrame = (data.size - 16) / frameCountOld
        else if (isNewFormat) bytesPerFrame = (data.size - 12) / frameCountOld
        else if ((data.size - 8) > 0 && (data.size - 8) % frameCountOld == 0) bytesPerFrame = (data.size - 8) / frameCountOld

        
        var frameCount = frameCountOld
        var fps = readU32(4)
        var playbackMode = 1 // Default to LOOP
        var audioOffsetMs = 0

        var offset = 8
        if (isFormatV3) {
            playbackMode = readU32(8)
            audioOffsetMs = readU32(12)
            offset = 16
        } else if (isNewFormat) {
            playbackMode = readU32(8)
            offset = 12
        } else {
            // Fallback for old format
            frameCount = readU32(0)
            fps = readU32(4)
            offset = 8
        }

        val result = ArrayList<IntArray>(frameCount)
        repeat(frameCount) {
            val frameBytes = ByteArray(bytesPerFrame)
            for (i in 0 until bytesPerFrame) {
                frameBytes[i] = data[offset + i]
            }
            result.add(MatrixConfig.formatForHardware(frameBytes))
            offset += bytesPerFrame
        }
        
        // We'll store playbackMode and offset in global variables for the Runnable to use
        currentPlaybackMode = playbackMode
        currentAudioOffsetMs = audioOffsetMs
        
        android.util.Log.d("OdysseyLyrics", "BaseToyService readFramesAsset: frameCount=${result.size} fps=$fps playbackMode=$playbackMode audioOffset=$audioOffsetMs")
        
        return Pair(result, if (fps <= 0) 12 else fps)
    }
}

class OdysseyToyServiceSlot1 : BaseToyService() {
    override fun getFramesFileName() = "frames_slot1.bin"
}

class OdysseyToyServiceSlot2 : BaseToyService() {
    override fun getFramesFileName() = "frames_slot2.bin"
}

class OdysseyToyServiceSlot3 : BaseToyService() {
    override fun getFramesFileName() = "frames_slot3.bin"
}
